### ISSUE TITLE
Error from tally.postTallyXML()

### ISSUE THREAD

**Issue by sreekupm** [dhananjay1405/tally-database-loader#16]
Dear Dhananjay, 

Please help to clear the below issue

Error from tally.postTallyXML() at 2022-08-16 16:11:56
Error: connect ECONNREFUSED ::1:9000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
connect ECONNREFUSED ::1:9000
ECONNREFUSED
connect
::1
--------------------------------------------------------------------------------

**Comment by sreekupm** [comment]
tally started, above  issue solved. but getting the below error 

    at Protocol._parsePacket (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\Connection.js:198:25)
    at Handshake.<anonymous> (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\dist\database.js:253:36)
    at Handshake.<anonymous> (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\Connection.js:526:10)
    at Handshake._callback (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\Connection.js:488:16)
    at Sequence.end (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Sequence.OkPacket (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
    at Protocol._parsePacket (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\sheeba\Downloads\tally-database-loader-utility-1.0.17\node_modules\mysql\lib\protocol\Parser.js:43:10)
ER_NO_SUCH_TABLE: Table 'tally.config' doesn't exist
ER_NO_SUCH_TABLE
Table 'tally.config' doesn't exist
42S02
truncate table config;
--------------------------------------------------------------------------------

**Comment by dhananjay1405** [comment]
Prima-facie this error signifies that

1. SQL Server is attempting to connect to Database named **tally** (since you mentioned this in config.json), but you did not created any such database. So you need to create database and specify exact name of that database in config.json schema setting (check for spelling mistakes)
2. Another possibility is you created database correctly, but forgot to create all the tables by executing table creation SQL script in **database-structure.sql** file

**Comment by sreekupm** [comment]
Dear Dhananjay, 
Thanks for the support. 
Issue resolved
