### ISSUE TITLE
Negative decimals not importing from CSV

### ISSUE THREAD

**Issue by prateeknagwani** [dhananjay1405/tally-database-loader#8]
Hi 
When trying to import negative discount from data
it throws the error

Error from database.bulkLoad() at 2021-07-19 19:38:19
Error converting data type varchar to numeric.
EREQUEST
RequestError: Error converting data type varchar to numeric.
    at Parser.<anonymous> (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\connection.js:1155:27)
    at Parser.emit (events.js:375:28)
    at Parser.<anonymous> (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\token-stream-parser.js:35:14)
    at Parser.emit (events.js:375:28)
    at addChunk (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Parser.Readable.push (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Parser.Transform.push (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at doneParsing (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\stream-parser.js:122:14)
    at C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5
DESKTOP-EL68VMP\SQLEXPRESS

--------------------------------------------------------------------------------

Error from tally.processMasters() at 2021-07-19 19:38:19
Error converting data type varchar to numeric.
EREQUEST
RequestError: Error converting data type varchar to numeric.
    at Parser.<anonymous> (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\connection.js:1155:27)
    at Parser.emit (events.js:375:28)
    at Parser.<anonymous> (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\token-stream-parser.js:35:14)
    at Parser.emit (events.js:375:28)
    at addChunk (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Parser.Readable.push (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Parser.Transform.push (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at doneParsing (C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\stream-parser.js:122:14)
    at C:\Users\Yash Nagwani\Downloads\tally-database-loader-main\tally-database-loader-main\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5
DESKTOP-EL68VMP\SQLEXPRESS

--------------------------------------------------------------------------------

The issue is that negative discounts are treated as varchar and negative discounts are treated in the form of "(-)10" for -10% discount.

guid | item | quantity | rate | amount | additional_amount | discount_amount | godown | tracking_number
-- | -- | -- | -- | -- | -- | -- | -- | --
1b78d2f6-6c21-4a81-a053-3dd0b7f6eec8-000000e1 | SAI168F H/L VISOR DIS/100 | 9 | 331.23 | -3815.77 | 0 | **(-)28** | Main Location

Please help for the fix

**Comment by prateeknagwani** [comment]
Corrected by changing

- name: discount_amount
          field: Discount
          type: number

to 

- name: discount_amount
          field: Discount
          type: amount

Please update in next release
